FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

# Instalamos dependencias y jq
RUN apt-get update && apt-get install -y \
    wget \
    jq \
    ca-certificates \
    libxext6 \
    libxrender1 \
    libxtst6 \
    libfreetype6 \
    libxi6 \
    libgtk-3-0 \
    libx11-xcb1 \
    xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Creamos el usuario
RUN useradd -ms /bin/bash developer
USER developer
WORKDIR /home/developer

# Obtener URL real del tar.gz con jq (mucho más fiable que grep)
RUN wget -qO idea_url.json "https://data.services.jetbrains.com/products/releases?code=IIC&latest=true&type=release" && \
    jq -r '.IIC[0].downloads.linux.link' idea_url.json > idea_url.txt && \
    wget -i idea_url.txt -O idea.tar.gz && \
    tar -xzf idea.tar.gz --strip-components=1 && \
    rm idea.tar.gz idea_url.json idea_url.txt

EXPOSE 8080

CMD ["bin/idea.sh"]
