# Imagen base con entorno XFCE accesible por navegador
FROM ghcr.io/linuxserver/webtop:ubuntu-xfce

# Versión de IntelliJ IDEA Community que quieres instalar
ENV IDEA_VERSION=2024.1.4

# Instalar dependencias y descargar IntelliJ Community
RUN apt-get update && \
    apt-get install -y wget tar && \
    wget -O /tmp/intellij.tar.gz https://download.jetbrains.com/idea/ideaIC-${IDEA_VERSION}.tar.gz && \
    mkdir -p /opt/intellij && \
    tar -xzf /tmp/intellij.tar.gz -C /opt/intellij --strip-components=1 && \
    rm /tmp/intellij.tar.gz && \
    ln -s /opt/intellij/bin/idea.sh /usr/local/bin/intellij
