version: "3.8"

services:
  intellij:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intellij
    ports:
      - "5901:5901"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - intellij_data:/home/developer
    restart: unless-stopped

volumes:
  intellij_data:
